controller_manager:
  ros__parameters:
    update_rate: 200  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_position_controller:
      type: position_controllers/JointGroupPositionController

arm_position_controller:
  ros__parameters:
    joints:
      - body_rotation
      - arm1_rotation
      - arm2_rotation
      - shovel_rotation
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

